apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: rust-app