apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rust-app
  name: rust-app
spec:
  ports:
  - name: 3000-8080
    port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    app: rust-app
  type: ClusterIP
status:
  loadBalancer: {}
