name: rust-demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
  

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker image
      run: docker build -t rust-demo .
    - name: Tag Docker image
      # run: docker tag rust-demo ghcr.io/${{ vars.REPO_USERNAME }}/rust-demo:latest
      run: docker tag rust-demo mostfullstack/rust-demo:latest
    - name: Push Docker image
    # run: docker push ghcr.io/${{ vars.REPO_USERNAME }}/rust-demo:latest
      run: docker push mostfullstack/rust-demo:latest