name: rust-demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Build Docker image
      run: docker build -t rust-app .
    - name: Push Docker image
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker tag rust-app ghcr.io/${{ secrets.DOCKER_USERNAME }}/rust-app:latest
    - run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/rust-app:latest


